name: DEPLOY_MAPPING_TASK

on:
  push

env:
  # was updated
  IICS_LOGIN_URL: https://dm-em.informaticacloud.com
  
  # ORIGINAL WAS
  # IICS_POD_URL: https://na1.dm-em.informaticacloud.com/saas
  # IICS_POD_URL: https://emw1.dm-em.informaticacloud.com/saas
  
  # IICS_USERNAME: ${{ secrets.IICS_USERNAME }}
  # IICS_PASSWORD: ${{ secrets.IICS_PASSWORD }}

  # UAT_IICS_USERNAME: ${{ secrets.UAT_IICS_USERNAME }}
  # UAT_IICS_PASSWORD: ${{ secrets.UAT_IICS_PASSWORD }}
  
jobs:
  connect:
    name: connection check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#       - name: Login to development 
#         env:
#           IICS_USERNAME: ${{ secrets.IICS_USERNAME }}
#           IICS_PASSWORD: ${{ secrets.IICS_PASSWORD }}
#         run: |
#           python ./scripts/infa_login.py  

      - name: Test
        env:
          IICS_PASSWORD: ${{ secrets.IICS_PASSWORD }}
        run: |
          if [ "$IICS_PASSWORD" == "123456789aA"] 
          then
            echo "got secret"
          fi
